### ISSUE TITLE
kategoriler.php SQL Injection Vulnerability

### ISSUE THREAD

**Issue by kdrypr** [onurrcoskun/Cms#1]
Hocam selamlar,

kategoriler.php sayfasında kategori id sini çağırdıktan sonra sql sorgusuna doğrudan input yapılmaktadır. Bu tip sorgularda dışarıdan gelen inputu doğrudan sorgulara yazdığın zaman zafiyet kaçınılmaz oluyor. Parametrik sorgu ile sorunu çözebilirsin. Benzer sorunlar search gibi sayfalarda da aynı şekilde giderilebilir.

    $stmt = $mysqli->prepare("SELECT * FROM posts  WHERE post_title=?");
    $stmt->bind_param("s", $post_kategori_selected);
    $stmt->execute();
    $result = $stmt->get_result();
    $stmt->close();
    $row = $result->fetch_array(MYSQLI_NUM);
    return $row;

daha sonrasında doğrudan row u while a sokabilirsin.

**Comment by onurrcoskun** [comment]
Selamlar Kadir Hocam,
Geri bildirim için teşekkür ederim.
Localde çalıştığım projelerden biri olduğunu için güvenlik tebdirlerini
biraz gözardı etmiştim.Ama verdiğiniz değerli bilgi için teşekkür ederim.

İyi Çalışmalar dilerim.
7 Eyl 2021 Sal, saat 16:05 tarihinde Kadir YAPAR ***@***.***>
şunu yazdı:
